### ISSUE TITLE
No longer working since update

### ISSUE THREAD

**Issue by noisiver** [azerothcore/aowow#20]
**Describe the bug and how to reproduce it**
Install the database viewer. It errors out almost instantly.

It tries to run the query and the columns it tries to use doesn't exist..

```
SELECT EnchantID AS ARRAY_KEY, Chance AS procChance, ratePerMinute AS ppmRate FROM spell_enchant_proc_data
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5157047/210898089-f08b5e55-82a0-48b1-97f6-05db44b3e2b1.png)

**System:**
 - OS: Ubuntu 22.04
 - PHP version: 8.2
 - revision used: 4b348afc3e84c38792ee3ef0893b1cd168352f97
 - Browser (in case of JavaScript / display errors):
 - AzerothCore: yes

**Comment by noisiver** [comment]
I downgraded to PHP 8.0 and it passed the above error but now it gets stuck elsewhere instead. See below.

![image](https://user-images.githubusercontent.com/5157047/210901173-63b6a50d-e71e-4e96-a651-7952aa9004ef.png)

**Comment by noisiver** [comment]
Just for the record, I did try the official repository by Sarjuuk, with TDB, and it works like it should with exactly the same version of PHP (8.0) and the same mpqdata.

**Comment by Helias** [comment]
I've just updated it and tested locally, download the master branch, it will work.

I am still doing some tests and check if there is some info missing

**Comment by noisiver** [comment]
I will test it now. Will respond when I know how it turns out. Thank you for taking the time with this, by the way.

You updated the README to say PHP > 7.1 but it won't run unless you have at least 8.0. Is that intentional?

**Comment by Helias** [comment]
you're right, you need PHP8+, I will update that detail

**Comment by noisiver** [comment]
It does get further along but now it crashes here instead
![image](https://user-images.githubusercontent.com/5157047/211059322-66c5bf59-aeca-407d-acf1-2bfe931fdd60.png)

**Comment by Helias** [comment]
try to update now please

**Comment by noisiver** [comment]
It's installing right now, just to let you know I'm on it.

**Comment by noisiver** [comment]
It did successfully install but now it can't show pages. I tried looking at npcs, objects, items and spells but they always say page not found. I tried forcing a sync of all the data and it still says it.
![image](https://user-images.githubusercontent.com/5157047/211123284-bc116a44-0b6f-4533-84e0-f0b9f3267950.png)

**Comment by noisiver** [comment]
Actually, gameobjects do seem to work. So does achievements, emotes, hunter pets, races, classes, titles, factions and a few other things. It seems to be mainly items, creatures and items that show a page not found error.

**Comment by noisiver** [comment]
Heh, it also stopped working because of updates to AzerothCore.
![image](https://user-images.githubusercontent.com/5157047/211127140-9acaed66-2e6c-4a36-b46b-d0a77208d492.png)

**Comment by Helias** [comment]
Please, contact me on Discord `Helias#1661`, so we can figure out easily any related issue.

**Comment by noisiver** [comment]
I've downloaded the specific commit of AzerothCore that you linked and I made sure to have the latest commit of this repository. It's currently installing and if I still have the same issue - the one saying page not found - , should I bother posting here or just go straight to Discord?

**Comment by Helias** [comment]
you can ping me on discord for this
