### ISSUE TITLE
Vendor tab for items not showing

### ISSUE THREAD

**Issue by noisiver** [azerothcore/aowow#24]
**Describe the bug and how to reproduce it**
The `Sold by` tab when viewing items isn't showing.

**Screenshots**
![image](https://user-images.githubusercontent.com/5157047/211192247-7bd0476e-1734-4a59-94c1-2e390bb6be10.png)

**System:**
 - OS: Ubuntu 22.04
 - PHP version: 8.0.27
 - revision used: 380aff2fc593989e13a440e3cfaf0f00ee88b0f2
 - Browser (in case of JavaScript / display errors): Firefox
 - AzerothCore: Yes

**Comment by noisiver** [comment]
Error message:
`/includes/types/item.class.php : line 114 : foreach() argument must be of type array|object, bool given`

**Comment by Helias** [comment]
if you put in the description of the PR 
"closes https://github.com/azerothcore/aowow/issues/24"
when the PR is merged the related issue is closed automatically ;-)

Thanks again for your contribution and to take care of issues

**Comment by noisiver** [comment]
> 

Right, I forgot to do that. Thanks!
