### ISSUE TITLE
Viewing maps of quests is sometimes acting up

### ISSUE THREAD

**Issue by noisiver** [azerothcore/aowow#25]
**Describe the bug and how to reproduce it**
Viewing certain quests show the shown map as merely a line across the site. Check the first screenshot below.

If you click `Tip: Click map to zoom`, the map will show as a bigger version and if you click that it'll show as the regular size properly. Check the second screenshot below.

I think this is related to the version of PHP used, just like PHP 8.1 and 8.2 do not work on my end at all which we discussed on Discord.

https://wowgaming.altervista.org/aowow/?quest=24557 always work as it should which truly leaves me to believe it's the version of PHP.

**Screenshots**
![image](https://user-images.githubusercontent.com/5157047/211192490-4b7648a3-d02c-4ac8-ba84-7e81316d5346.png)
![image](https://user-images.githubusercontent.com/5157047/211192512-843f0937-4025-4584-bf7c-30a87564d04b.png)

**System:**
 - OS: Ubuntu 22.04
 - PHP version: 8.0.27
 - revision used: 380aff2fc593989e13a440e3cfaf0f00ee88b0f2
 - Browser (in case of JavaScript / display errors): Firefox
 - AzerothCore: Yes

**Comment by noisiver** [comment]
I don't know what happened but I reinstalled my PCs today and the issue seems to be gone. I guess something in Firefox messed it up before. I'm closing this issue and if it starts to happen again I'll reopen it.

**Comment by Helias** [comment]
it's always a bit hard working with AoWoW
