### ISSUE TITLE
Quick stats isn't showing any stats

### ISSUE THREAD

**Issue by noisiver** [azerothcore/aowow#27]
**Describe the bug and how to reproduce it**
The quick stats box on the right side of *everything* is empty. For quests it shows what it requires or opens but nothing else.

I believe this is yet another thing affected by the version of PHP.

**Screenshots**
![image](https://user-images.githubusercontent.com/5157047/211219870-c2f1b52f-f327-43bf-aff5-a23367c493f5.png)
![image](https://user-images.githubusercontent.com/5157047/211219960-46d3e6c4-b7cf-4933-84c1-207af1c07602.png)
![image](https://user-images.githubusercontent.com/5157047/211220016-013a281b-550b-4b2a-b951-6cdcd3d5f86c.png)

**System:**
 - OS: Ubuntu 22.04
 - PHP version: 8.0.27
 - revision used: 380aff2fc593989e13a440e3cfaf0f00ee88b0f2
 - Browser (in case of JavaScript / display errors): Firefox
 - AzerothCore: Yes

**Comment by Helias** [comment]
This usually depends also on Markup.js, be sure to have it in `static/js/` with the right permissions
is it reproducible on wowgaming?

**Comment by noisiver** [comment]
No, it wasn't. After I did a full reinstall I totally forgot to make sure it was there. Copying it did fix the problem. Thank you for reminding me of that.
