### ISSUE TITLE
Some creatures can't be viewed at all

### ISSUE THREAD

**Issue by noisiver** [azerothcore/aowow#28]
**Describe the bug and how to reproduce it**
A few creatures can't be viewed at all. I can't give an exact list since I'm not going to go through every single creature but I have found one just randomly. There may be items, quests, spells  or anything else too but I haven't encountered one of those yet.

https://wowgaming.altervista.org/aowow/?npc=14378

It doesn't work there either so that's easy to test.

The creature does exist in `aowow_creature` so it's imported and it does show up in the list of NPCs when looking at Darnassus.

**Screenshots**

**System:**
 - OS: Ubuntu 22.04
 - PHP version: 8.0.27
 - revision used: 380aff2fc593989e13a440e3cfaf0f00ee88b0f2
 - Browser (in case of JavaScript / display errors): Firefox
 - AzerothCore: Yes

**Comment by neifion-00000000** [comment]
https://wowgaming.altervista.org/aowow/?npc=822 is missing as well, as well as the ability to report errors

**Comment by noisiver** [comment]
I'll make sure to include the error message.

`/pages/npc.php : line 376 : array_pop(): Argument #1 ($array) must be of type array, bool given`

Seems to be related to SmartAI.
