### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by ForevergloryXXI** [azerothcore/aowow#38]
**Describe the bug and how to reproduce it**

- Hei im newbie in this, I just set up the AzerotCore, and now I want to install this tool
- The problem is I don't understand the installation guide, I clone it from GitHub
- I import the db_structure.sql in heidisql on "acore_characters" and now
- I don't know if what I was doing was good, can someone help me please im lost
- I was search on YouTube and google for some videos guides but didn't find
- Can someone help me install it or give to me a guide or something please I really want to install it

**Screenshots**
https://imgur.com/a/3LSABt4

**System:**
 - OS: [e.g. Win10]
 - PHP version: last version
 - revision used:
 - Browser (in case of JavaScript / display errors):Opera
 - AzerothCore: yes

**Comment by Helias** [comment]
`I import the db_structure.sql in heidisql on "acore_characters" and now`

You should create an `aowow` database and put the db_structure there.

Configuring AoWoW is not the easiest thing to do, I would like to make a docker container about it, it could help a lot.

I wrote several details in the README.md including the troubleshooting.
The first time I tried to install it, it was very hard, now with the details in the readme should be easier.

Anyways, if you need any help you can ask support in the azerothcore discord server in the `#web` channel under the `TOOLS` category, you can tag me there, hope I can help you.
