### ISSUE TITLE
problems with player_levelstats

### ISSUE THREAD

**Issue by spacefox-platforms** [azerothcore/aowow#39]
**Describe the bug and how to reproduce it**
running the setup script, once it starts gathering data for statistics, the crashes because acore_world.player_levelstats does not exist
i found this [pull request](https://github.com/azerothcore/azerothcore-wotlk/pull/14383) where the azerothcore team split player_levelstats into two new tables, player_class_stats and player_race_stats.

**Screenshots**
![image](https://github.com/azerothcore/aowow/assets/121242218/589582ef-c4eb-4435-8df7-07b45d01a009)

**System:**
 - OS: Debian 12
 - PHP version: 8.2.7
 - revision used:
 - Browser (in case of JavaScript / display errors): NA
 - AzerothCore: yes

**Comment by Helias** [comment]
This is an issue also of the main AoWoW version maintained by Sarjiuuk

**Comment by Helias** [comment]
this issue should be kind "solved" by https://github.com/azerothcore/aowow/pull/48
I do not know if my approach was the best, but at least you should not get any error now
